name: Get Unity License Request

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      # Робот скачивает ваш реальный репозиторий с созданной папкой ProjectSettings
      - uses: actions/checkout@v4

      # Теперь он сканирует корень, находит ProjectVersion.txt и понимает версию
      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v3

      # Выкладывает готовый файл запроса лицензии
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ./*.alf
